#!/bin/bash
bsr_session_on_prompt() {
    history -a
    pwd > ${SESSION_DIR}/pwd
}

bsr_init() {
    if [[ -z "$SESSION_NAME" ]]; then
        SESSION_NAME="$1"
    fi
    SESSION_DIR="${HOME}/.bash_sessions/$SESSION_NAME"
    mkdir -p "${SESSION_DIR}"
    HISTFILE="${SESSION_DIR}/history"
    OLD_PROMPT_COMMAND="$PROMPT_COMMAND"
    PROMPT_COMMAND="$PROMPT_COMMAND; bsr_session_on_prompt"
    BSR_ACTIVE=true
    echo -n $WINDOWID > "$SESSION_DIR"/winid
    echo -n $$ > ${SESSION_DIR}/pid
}

bsr_enter() {
    if [[ true == $BSR_ACTIVE ]]; then
        echo "already in a session: \"$SESSION_NAME\", not entering another"
        return;
    fi
    bsr_init "$1"
    history -c
    history -r
    cd $(cat ${SESSION_DIR}/pwd)
    echo "Entering session: $1"
}

bsr_create() {
    echo -- $BSR_ACTIVE
    if [[ "true" == $BSR_ACTIVE ]]; then
        echo "already in a session: \"$SESSION_NAME\", not creating another"
        return;
    fi
    echo "Creating Session: $1"
    bsr_init "$1"
    bsr_session_on_prompt
    echo "Entering Session: $1"
}


bsr_list() {
    for S in ${HOME}/.bash_sessions/*/; do
        pid="$(cat ${S}pid 2>/dev/null)";
        if [[ -z $pid ]]; then
           sigil="[D]"
        elif ps "$pid" | grep -q bash; then
            sigil="[A]"
        else
            sigil="[D]"
        fi
        name=$(basename "$S")
        echo "$name    $sigil"
    done
}
