#!/bin/bash
bsr_session_on_prompt() {
    history -a
    pwd > ${SESSION_DIR}/pwd
}

bsr_init() {
    if [[ -z "$SESSION_NAME" ]]; then
        SESSION_NAME="$1"
    fi
    SESSION_DIR="${HOME}/.bash_sessions/$SESSION_NAME"
    mkdir -p "${SESSION_DIR}"
    HISTFILE="${SESSION_DIR}/history"
    OLD_PROMPT_COMMAND="$PROMPT_COMMAND"
    PROMPT_COMMAND="$PROMPT_COMMAND; session_on_prompt"
    BSR_ACTIVE=true
    echo $WINDOWID > "$SESSION_DIR"/winid
}

bsr_enter() {
    bsr_init "$1"
    history -c
    history -r
    cd $(cat ${SESSION_DIR}/pwd)
    echo "Entering session: $1"
}

bsr_create() {
    if [[ $BSR="true" ]]; then
        exit;
    fi
    echo "Creating Session: $1"
    bsr_init "$1"
    bsr_session_on_prompt
    echo "Entering Session: $1"
}

